# Generated by Django 5.1.5 on 2025-03-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Event Name')),
                ('date', models.DateField(verbose_name='Event Date')),
                ('description', models.TextField(blank=True, verbose_name='Event Description')),
            ],
        ),
    ]
